### PR TITLE
NEW: Add FAQ pages

### PR DESCRIPTION
**Pull request by ilhanmercan**

### CODE REVIEW

**Comment by vesellov** [comment]
it can be done more easy: as a static .html files one the server...

**Comment by ilhanmercan** [comment]
> it can be done more easy: as a static .html files one the server...

I removed all of the content on those files. We can decide later how/where to put

**Comment by ilhanmercan** [comment]
@vesellov it should be better now as the content of the FAQ is removed.

**Comment by vesellov** [comment]
Good start! 👍 
Nice @ilhanmercan

**Pull request merged**
